### ISSUE TITLE
documentation error preventing package installation

### ISSUE THREAD

**Issue by ambertin** [SmithCollege-SDS/sds#11]
I get this error when trying to install the sds package, which prevents me from being able to download it. All my packages are up to date.

Error : (converted from warning) bad markup (extra space?) at moon_reader.Rd:39:13
ERROR: installing Rd objects failed for package ‘sds’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sds’
Error: Failed to install 'sds' from GitHub

**Comment by rudeboybert** [comment]
Hey @ambertin can you try again? It seems the `roxygen2` help files got stale & needed rebuilding.

**Comment by ambertin** [comment]
Seems to be working now. Thanks @rudeboybert!
