### ISSUE TITLE
package installation fails with 'icon' dependency issue

### ISSUE THREAD

**Issue by ambertin** [SmithCollege-SDS/sds#15]
`remotes::install_github("SmithCollege-SDS/sds")` results in the following error, which prohibits installation of the package:

ERROR: dependency ‘icon’ is not available for package ‘sds’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sds’
Error: Failed to install 'sds' from GitHub:
  (converted from warning) installation of package ‘/var/folders/v6/f62qz88s0sd5n3yqw9d8sb300000gn/T//RtmpYMZuqv/file802946100c7a/sds_0.0.2.9003.tar.gz’ had non-zero exit status

**Comment by beanumber** [comment]
Looks like this changed:

https://github.com/mitchelloharawild/icons

I was using `ropensci/icon`, but I guess that is now superseded by `mitchelloharawild/icons`. Can send a PR with a fix?
